version: '3'

services:

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./api-gateway:/app
    networks:
      - app-network
    links:
      - user-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./user-service:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge