version: '3'

services:
    # api-gateway
    api-gateway:
        build:
            context: ./api-gateway
            dockerfile: Dockerfile
        ports:
            - "8081:8081"
            - "9876:9876"
        volumes:
            - ./api-gateway:/app
        networks:
            - gateway
        links:
            - data-service
            - product-service
        command: 
            - nodemon 
            - .
    
    # data-service
    data-service:
        build:
            context: ./data-service
            dockerfile: Dockerfile
        ports:
            - "3003:3003"
        volumes:
            - ./data-service:/app
        networks:
            - gateway
        links:
            - eg_redis
        command: 
            - nodemon 
            - .
    
    # product-service
    product-service:
        build:
            context: ./product-service
            dockerfile: Dockerfile
        ports:
            - "3002:3002"
        volumes:
            - ./product-service:/app
        networks:
            - gateway
        links:
            - eg_redis
        command: 
            - nodemon 
            - .
    
    # user-service
    user-service:
        build:
            context: ./user-service
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        volumes:
            - ./user-service:/app
        networks:
            - gateway
        links:
            - eg_redis
        command: 
            - nodemon 
            - .

    # redis database
    eg_redis:
        image: redis
        hostname: redis
        container_name: redisdocker
        ports:
            - "6379:6379"
        networks:
            gateway:
                aliases:
                   - redis
    #express gateway
    # express_gateway:
    #     build: .
    #     container_name: egdocker
    #     ports:
    #         - "8081:8081"
    #         - "8443:8443"
    #         - "9876:9876"
    #     volumes:
    #         - ./system.config.yml:/usr/src/app/config/system.config.yml
    #         - ./gateway.config.yml:/usr/src/app/config/gateway.config.yml
    #     networks:
    #         - gateway
    #mysql
    # eg_sql:
    #     image: mysql:5.7
    #     volumes:
    #         - db_data:/var/lib/mysql
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: tasikmalaya
    #         MYSQL_DATABASE: test
    #         MYSQL_USER: test
    #         MYSQL_PASSWORD: test123
    #     networks:
    #         gateway:
    #             aliases:
    #                 - mysql
    #phpmyadmin
    # phpmyadmin:
    #     depends_on:
    #         - eg_sql
    #     image: phpmyadmin/phpmyadmin
    #     restart: always
    #     ports:
    #         - '8080:80'
    #     environment:
    #         PMA_HOST: db
    #         MYSQL_ROOT_PASSWORD: tasikmalaya 
    #     networks:
    #         - gateway 
networks:
    gateway: